;/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lineage;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author instal
 */
public class lineage extends javax.swing.JFrame {
   ArrayList<String[]> action = new ArrayList<String[]>();
   String[] pole;
  int age0;
  int age1;
  int age2;
  int age3;
  int age4;
  int age5;
  int age6;
  int age7;
  int age8;
  int age9;
  int age10;
  int age11;
  int age12;
  int age13;
  int age14;
  
  
    public lineage() {
        initComponents(); 
        
         try {           
            FileReader fr=new FileReader(System.getProperty("user.home")+"//Desktop//rodokmen.txt");
            BufferedReader br=new BufferedReader(fr);
            String kokot=null;
            while((kokot=br.readLine()) !=null){          
            pole =kokot.split(",");
            //System.out.println(Arrays.toString(pole));
            action.add(pole);
            }
            
            System.out.println(action.get(0)[0]);
             jButton1.setText(action.get(0)[0]);
            jButton2.setText(action.get(1)[0]);
             jButton3.setText(action.get(2)[0]);
              jButton4.setText(action.get(3)[0]);
               jButton5.setText(action.get(4)[0]);
                jButton6.setText(action.get(5)[0]);
                 jButton7.setText(action.get(6)[0]);
                  jButton8.setText(action.get(7)[0]);
                   jButton9.setText(action.get(8)[0]);
                    jButton10.setText(action.get(9)[0]);
                     jButton11.setText(action.get(10)[0]);
                      jButton12.setText(action.get(11)[0]);
                       jButton13.setText(action.get(12)[0]);
                        jButton14.setText(action.get(13)[0]);
                         jButton15.setText(action.get(14)[0]);
            }   catch (FileNotFoundException ex) {
                    Logger.getLogger(lineage.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(lineage.class.getName()).log(Level.SEVERE, null, ex);
                }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();

        setTitle("Lineage");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");

        jButton3.setText("jButton3");

        jButton4.setText("jButton4");

        jButton5.setText("jButton5");

        jButton6.setText("jButton6");

        jButton7.setText("jButton7");

        jButton8.setText("jButton8");

        jButton9.setText("jButton9");

        jButton10.setText("jButton10");

        jButton11.setText("jButton11");

        jButton12.setText("jButton12");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setText("jButton13");

        jButton14.setText("jButton14");

        jButton15.setText("jButton15");

        jButton16.setText("jButton16");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jButton17.setText("jButton17");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton9)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton1)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton2)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton10)
                                .addGap(226, 226, 226))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(231, 231, 231)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton4))
                                    .addComponent(jButton13)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton17)
                                        .addGap(83, 83, 83)))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton5)
                                    .addComponent(jButton14))
                                .addGap(16, 16, 16)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton11)
                            .addComponent(jButton6))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jButton12))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jButton7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton8))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(373, 373, 373)
                        .addComponent(jButton15))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jButton16)))
                .addContainerGap(252, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton5)
                    .addComponent(jButton4)
                    .addComponent(jButton3)
                    .addComponent(jButton2)
                    .addComponent(jButton1)
                    .addComponent(jButton7)
                    .addComponent(jButton8))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton11)
                    .addComponent(jButton12)
                    .addComponent(jButton9)
                    .addComponent(jButton10))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton14)
                    .addComponent(jButton13))
                .addGap(64, 64, 64)
                .addComponent(jButton15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton16)
                    .addComponent(jButton17))
                .addGap(269, 269, 269))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
         try {
            ArrayList<String[]> action = new ArrayList<String[]>();
            FileReader fr=new FileReader(System.getProperty("user.home")+"//Desktop//rodokmen.txt");
            BufferedReader br=new BufferedReader(fr);
            String kokot=null;
            while((kokot=br.readLine()) !=null){          
            String[] pole =kokot.split(",");
            //System.out.println(Arrays.toString(pole));
            action.add(pole);
            }
            
            System.out.println(action.get(0)[0]);
             jButton1.setText(action.get(0)[0]);
            jButton2.setText(action.get(1)[0]);
             jButton3.setText(action.get(2)[0]);
              jButton4.setText(action.get(3)[0]);
               jButton5.setText(action.get(4)[0]);
                jButton6.setText(action.get(5)[0]);
                 jButton7.setText(action.get(6)[0]);
                  jButton8.setText(action.get(7)[0]);
                   jButton9.setText(action.get(8)[0]);
                    jButton10.setText(action.get(9)[0]);
                     jButton11.setText(action.get(10)[0]);
                      jButton12.setText(action.get(11)[0]);
                       jButton13.setText(action.get(12)[0]);
                        jButton14.setText(action.get(13)[0]);
                         jButton15.setText(action.get(14)[0]);
                         
                      
                   
            
        } catch (IOException ex) {
            Logger.getLogger(lineage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         new info().setVisible(true);
         info.jTextField1.setText(action.get(0)[0]);
         int age=Integer.parseInt(action.get(0)[3]) - Integer.parseInt(action.get(0)[2]);
         info.jTextField2.setText(String.valueOf(age));
         info.jTextField3.setText(action.get(0)[2]);
         info.jTextField4.setText(action.get(0)[3]);
         info.jTextField5.setText(action.get(0)[4]);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
       new life().setVisible(true);
      //----------------------------------------------------------------------------------------------------------
      if((action.get(0)[3]).equals(String.valueOf(0))){
          int year=Calendar.getInstance().get(Calendar.YEAR);
         age0=(year -(Integer.parseInt(action.get(0)[2]))); 
      }
      else {
          age0=Integer.parseInt(action.get(0)[3]) - Integer.parseInt(action.get(0)[2]);}
      //----------------------------------------------------------------------------------------------------------
      if((action.get(1)[3]).equals(String.valueOf(0))){
          int year=Calendar.getInstance().get(Calendar.YEAR);
         age1=(year -(Integer.parseInt(action.get(1)[2]))); 
      }
      else {
          age1=Integer.parseInt(action.get(1)[3]) - Integer.parseInt(action.get(1)[2]);}
      //----------------------------------------------------------------------------------------------------------
      if((action.get(2)[3]).equals(String.valueOf(0))){
          int year=Calendar.getInstance().get(Calendar.YEAR);
         age2=(year -(Integer.parseInt(action.get(2)[2]))); 
      }
      else {
          age2=Integer.parseInt(action.get(2)[3]) - Integer.parseInt(action.get(2)[2]);}
       //----------------------------------------------------------------------------------------------------------
      if((action.get(3)[3]).equals(String.valueOf(0))){
          int year=Calendar.getInstance().get(Calendar.YEAR);
         age3=(year -(Integer.parseInt(action.get(3)[2]))); 
      }
      else {
          age3=Integer.parseInt(action.get(3)[3]) - Integer.parseInt(action.get(3)[2]);}
      //----------------------------------------------------------------------------------------------------------
      
       if((action.get(4)[3]).equals(String.valueOf(0))){
          int year=Calendar.getInstance().get(Calendar.YEAR);
         age4=(year -(Integer.parseInt(action.get(4)[2]))); 
      }
      else {
          age4=Integer.parseInt(action.get(4)[3]) - Integer.parseInt(action.get(4)[2]);}
       //----------------------------------------------------------------------------------------------------------
      if((action.get(5)[3]).equals(String.valueOf(0))){
          int year=Calendar.getInstance().get(Calendar.YEAR);
         age5=(year -(Integer.parseInt(action.get(5)[2]))); 
      }
      else {
          age5=Integer.parseInt(action.get(5)[3]) - Integer.parseInt(action.get(5)[2]);}
       //----------------------------------------------------------------------------------------------------------
      if((action.get(6)[3]).equals(String.valueOf(0))){
          int year=Calendar.getInstance().get(Calendar.YEAR);
         age6=(year -(Integer.parseInt(action.get(6)[2]))); 
      }
      else {
          age6=Integer.parseInt(action.get(6)[3]) - Integer.parseInt(action.get(6)[2]);}
      //----------------------------------------------------------------------------------------------------------
       if((action.get(7)[3]).equals(String.valueOf(0))){
          int year=Calendar.getInstance().get(Calendar.YEAR);
         age7=(year -(Integer.parseInt(action.get(7)[2]))); 
      }
      else {
          age7=Integer.parseInt(action.get(7)[3]) - Integer.parseInt(action.get(7)[2]);}
      //----------------------------------------------------------------------------------------------------------
      if((action.get(8)[3]).equals(String.valueOf(0))){
          int year=Calendar.getInstance().get(Calendar.YEAR);
         age8=(year -(Integer.parseInt(action.get(8)[2]))); 
      }
      else {
          age8=Integer.parseInt(action.get(8)[3]) - Integer.parseInt(action.get(8)[2]);}
       //----------------------------------------------------------------------------------------------------------
      if((action.get(9)[3]).equals(String.valueOf(0))){
          int year=Calendar.getInstance().get(Calendar.YEAR);
         age9=(year -(Integer.parseInt(action.get(9)[2]))); 
      }
      else {
          age9=Integer.parseInt(action.get(9)[3]) - Integer.parseInt(action.get(9)[2]);}
       //----------------------------------------------------------------------------------------------------------
       if((action.get(10)[3]).equals(String.valueOf(0))){
          int year=Calendar.getInstance().get(Calendar.YEAR);
         age10=(year -(Integer.parseInt(action.get(10)[2]))); 
      }
      else {
          age10=Integer.parseInt(action.get(10)[3]) - Integer.parseInt(action.get(10)[2]);}
       //----------------------------------------------------------------------------------------------------------
        if((action.get(11)[3]).equals(String.valueOf(0))){
          int year=Calendar.getInstance().get(Calendar.YEAR);
         age11=(year -(Integer.parseInt(action.get(11)[2]))); 
      }
      else {
          age11=Integer.parseInt(action.get(11)[3]) - Integer.parseInt(action.get(11)[2]);}
      //----------------------------------------------------------------------------------------------------------
       if((action.get(12)[3]).equals(String.valueOf(0))){
          int year=Calendar.getInstance().get(Calendar.YEAR);
         age12=(year -(Integer.parseInt(action.get(12)[2]))); 
      }
      else {
          age12=Integer.parseInt(action.get(12)[3]) - Integer.parseInt(action.get(12)[2]);}
      //----------------------------------------------------------------------------------------------------------
       if((action.get(13)[3]).equals(String.valueOf(0))){
          int year=Calendar.getInstance().get(Calendar.YEAR);
         age13=(year -(Integer.parseInt(action.get(13)[2]))); 
      }
      else {
          age13=Integer.parseInt(action.get(13)[3]) - Integer.parseInt(action.get(13)[2]);}
      //----------------------------------------------------------------------------------------------------------
       if((action.get(14)[3]).equals(String.valueOf(0))){
          int year=Calendar.getInstance().get(Calendar.YEAR);
         age14=(year -(Integer.parseInt(action.get(14)[2]))); 
      }
      else {
          age14=Integer.parseInt(action.get(14)[3]) - Integer.parseInt(action.get(14)[2]);}
      
      
      
      
      
      
    
     int maxNum=Math.max(age0, Math.max( age1, Math.max(age2,Math.max(age3,Math.max(age4,Math.max(age5,Math.max(age6,Math.max(age7,Math.max(age8,Math.max(age9,Math.max(age10,Math.max(age11,Math.max(age12,Math.max(age13,age14))))))))))) )));
     int minNum=Math.min(age0, Math.min( age1, Math.min(age2,Math.min(age3,Math.min(age4,Math.min(age5,Math.min(age6,Math.min(age7,Math.min(age8,Math.min(age9,Math.min(age10,Math.min(age11,Math.min(age12,Math.min(age13,age14))))))))))) )));
       
     life.jTextField3.setText(String.valueOf(maxNum));
     life.jTextField4.setText(String.valueOf(minNum));
    }//GEN-LAST:event_jButton17ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lineage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lineage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lineage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lineage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lineage().setResizable(false); 
            }     
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JButton jButton1;
    private static javax.swing.JButton jButton10;
    private static javax.swing.JButton jButton11;
    private static javax.swing.JButton jButton12;
    private static javax.swing.JButton jButton13;
    private static javax.swing.JButton jButton14;
    private static javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private static javax.swing.JButton jButton2;
    private static javax.swing.JButton jButton3;
    private static javax.swing.JButton jButton4;
    private static javax.swing.JButton jButton5;
    private static javax.swing.JButton jButton6;
    private static javax.swing.JButton jButton7;
    private static javax.swing.JButton jButton8;
    private static javax.swing.JButton jButton9;
    // End of variables declaration//GEN-END:variables
}
